apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: docker
  namespace: '{{ "NAMESPACE" | env }}'
data:
  .dockerconfigjson: '{{ (printf "{\"auths\": {\"%s\": {\"auth\":\"%s\"}}}" ("DOCKER_REGISTRY" | env) ((printf "%s:%s" ("DOCKER_REGISTRY_KEY" | env | teamvaultUser) ("DOCKER_REGISTRY_KEY" | env | teamvaultPassword)) | base64)) | base64}}'
  password: '{{"DOCKER_REGISTRY_KEY" | env | teamvaultPassword | base64}}'
  username: '{{"DOCKER_REGISTRY_KEY" | env | teamvaultUser | base64}}'
