apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: docker
  namespace: 'teamvault'
data:
  .dockerconfigjson: '{{ (printf "{\"auths\": {\"%s\": {\"auth\":\"%s\"}}}" ("DOCKER_REGISTRY" | env) ((printf "%s:%s" ("BwjYGq" | teamvaultUser) ("BwjYGq" | teamvaultPassword)) | base64)) | base64}}'
  password: '{{"BwjYGq" | teamvaultPassword | base64}}'
  username: '{{"BwjYGq" | teamvaultUser | base64}}'
