apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: ldap
  namespace: '{{ "NAMESPACE" | env }}'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ldap
  serviceName: ldap
  template:
    metadata:
      labels:
        app: ldap
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node_type
                    operator: In
                    values:
                      - 'longhorn'
      containers:
        - name: service
          env:
            - name: DISABLE_CHOWN
              value: 'true'
            - name: LDAP_SUFFIX
              value: 'dc=benjamin-borbe,dc=de'
            - name: LDAP_ROOTDN
              value: 'cn=root,dc=benjamin-borbe,dc=de'
            - name: LDAP_SECRET
              valueFrom:
                secretKeyRef:
                  key: ldap-secret
                  name: ldap
          image: '{{"DOCKER_REGISTRY" | env}}/openldap:{{"LDAP_VERSION" | env}}'
          imagePullPolicy: Always
          ports:
            - containerPort: 389
              name: ldap
            - containerPort: 636
              name: ldaps
          resources:
            limits:
              cpu: 500m
              memory: 75Mi
            requests:
              cpu: 20m
              memory: 20Mi
          volumeMounts:
            - mountPath: /var/lib/openldap
              name: datadir
      imagePullSecrets:
        - name: docker-fire
        - name: docker-quant
  updateStrategy:
    type: RollingUpdate
  volumeClaimTemplates:
    - metadata:
        name: datadir
      spec:
        storageClassName: longhorn
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
