apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: postgres
  namespace: '{{ "NAMESPACE" | env }}'
data:
  postgres-password: '{{ "POSTGRES_PASSWORD_KEY" | env | teamvaultPassword | base64 }}'
