apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: teamvault
  namespace: 'teamvault'
data:
  ldap-secret: '{{ "LDAP_SECRET_KEY" | env | teamvaultPassword | base64 }}'
  postgres-password: '{{ "POSTGRES_PASSWORD_KEY" | env | teamvaultPassword | base64 }}'
  secret-key: '{{ "TEAMVAULT_SECRET_KEY" | env | teamvaultPassword | base64 }}'
  fernet-key: '{{ "TEAMVAULT_FERNET_KEY" | env | teamvaultPassword | base64 }}'
  salt: '{{ "TEAMVAULT_SALT_KEY" | env | teamvaultPassword | base64 }}'
