apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: teamvault
  namespace: 'teamvault'
spec:
  ingressClassName: 'traefik'
  rules:
    - host: 'teamvault.benjamin-borbe.de'
      http:
        paths:
          - backend:
              service:
                name: teamvault
                port:
                  name: http
            path: /
            pathType: Prefix
